### ISSUE TITLE
Example `demo-ssr` not working

### ISSUE THREAD

**Issue by JosVerheij** [lpotthast/leptos-tiptap#2]
I am unable to get leptos-tiptap to work in an SSR environment with axum. Using tag leptos-tiptap/v0.6.0 results in a Tiptap instance that does not seem to run.

Running the example `demo-ssr` results in an empty editor field, where normally (editable and formatted) content would be displayed. The "HTML Output" field below the editor does show the example paragraph, but it is unformatted (as intended). Running `demo-csr` does have a working Tiptap editor instance.

I encounter the same issue after integrating leptos-tiptap in my own project.

If it matters, running `cargo leptos watch` in the demo-ssr directory results in the error below. The demo can only be started with `cargo run --feature ssr`. 

```
...
Front compiling WASM
Error: at `/Users/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.7/src/compile/front.rs:47:30`

Caused by:
    0: at `/Users/USER/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-leptos-0.2.7/src/compile/front.rs:120:10`
    1: 
       
       it looks like the Rust project used to create this wasm file was linked against
       version of wasm-bindgen that uses a different bindgen format than this binary:
       
         rust wasm file schema version: 0.2.92
            this binary schema version: 0.2.91
       
       Currently the bindgen format is unstable enough that these two schema versions
       must exactly match. You can accomplish this by either updating this binary or 
       the wasm-bindgen dependency in the Rust project.
       
       You should be able to update the wasm-bindgen dependency with:
       
           cargo update -p wasm-bindgen --precise 0.2.91
       
       don't forget to recompile your wasm file! Alternatively, you can update the 
       binary with:
       
           cargo install -f wasm-bindgen-cli --version 0.2.92
       
       if this warning fails to go away though and you're not sure what to do feel free
       to open an issue at https://github.com/rustwasm/wasm-bindgen/issues!
       
```

Either of the suggested commands does not alleviate the issue of running through `cargo leptos watch`.

```
$ rustup --version
info: The currently active `rustc` version is `rustc 1.76.0 (07dca489a 2024-02-04)`
```

I'm fairly new to both leptos and rust. If I can provide any additional information that is useful, please let me know.

**Comment by RamirezAlex** [comment]
Have you tried running:
```
cargo install -f wasm-bindgen-cli --version 0.2.92
cargo update -p wasm-bindgen --precise 0.2.91
```
in your terminal?

**Comment by lpotthast** [comment]
@JosVerheij This can come from time to time when you have non matching versions installed. As you can also see from the logs, the error originated in `cargo-leptos`. As @RamirezAlex already pointed out, performing the two commands mentioned or just doing a 
```
cargo install cargo-leptos
cargo install wasm-bindgen-cli
cargo install wasm-bindgen
```
so that everything is up-to-date (which should generally work well together) should do the trick.

**Comment by JosVerheij** [comment]
My bad. I had an older version of cargo-leptos installed (`0.2.7`). Updated to `0.2.16` by running `cargo install cargo-leptos` and I can get the example running.

Had not noticed cargo-leptos was apparently not updated through running cargo update. 

Thanks for your help!
